export const enum WorkerMessageType
{
    INIT_CORE ,
    PLAYER_HAS_A_MOVE_TODO,
    NOTIFY_PROMOTION,
    NOTIFY_MOVE ,
    GET_POSSIBLE_DESTINATIONS ,
    KING_IS_IN_DANGER,
    REALIZE_CAPTURE,
    CAN_DO_EN_PASSANT_CAPTURE ,
    CASE_IS_EMPTY,
    CASE_OCCUPIED_BY_OPPONENT,
    GET_BEST_MOVE_POSSIBLE,
    CAN_MAKE_RIGHT_CASTLING,
    CAN_MAKE_LEFT_CASTLING,
    KILL_CORE
}
